import { db } from "@/platform/database/client";
import { forbidden } from "@/platform/errors";
import { isUuid } from "@/platform/validation/uuid";
import { membershipHasPermission } from "./policy";

export const PERMISSIONS = {
  organisationManageMembers: "organisation.manage_members",
  propertyCreate: "property.create",
  propertyRead: "property.read",
  propertyUpdate: "property.update",
  portfolioCreate: "portfolio.create",
  auditRead: "audit.read",
  tenantCreate: "tenant.create",
  tenantRead: "tenant.read",
  tenantUpdate: "tenant.update",
  leaseCreate: "lease.create",
  leaseRead: "lease.read",
  leaseUpdate: "lease.update",
  reminderManage: "reminder.manage",
  rentScheduleManage: "rent_schedule.manage",
  paymentRead: "payment.read",
  paymentRecord: "payment.record",
  paymentReverse: "payment.reverse",
  depositRead: "deposit.read",
  depositRecord: "deposit.record",
  ledgerRead: "ledger.read",
  maintenanceRead: "maintenance.read",
  maintenanceCreate: "maintenance.create",
  maintenanceManage: "maintenance.manage",
  maintenanceApprove: "maintenance.approve",
  maintenanceAssign: "maintenance.assign",
  maintenanceCost: "maintenance.cost",
  providerRead: "provider.read",
  providerManage: "provider.manage",
  providerVerify: "provider.verify",
  providerQuoteRecord: "provider.quote_record",
  providerQuoteReview: "provider.quote_review",
  providerAssign: "provider.assign",
  providerRate: "provider.rate",
  marketplaceEnquiryCreate: "marketplace.enquiry.create",
  marketplaceEnquiryRead: "marketplace.enquiry.read",
  marketplaceEnquiryManage: "marketplace.enquiry.manage",
  marketplaceQuoteRequest: "marketplace.quote_request",
  listingCreate: "listing.create",
  listingRead: "listing.read",
  listingManage: "listing.manage",
  listingPublish: "listing.publish",
  listingVerify: "listing.verify",
  listingLeadRead: "listing.lead.read",
  listingLeadManage: "listing.lead.manage",
  listingViewingRead: "listing.viewing.read",
  listingViewingManage: "listing.viewing.manage",
  applicationCreate: "application.create",
  applicationRead: "application.read",
  applicationReview: "application.review",
  applicationConvert: "application.convert",
  leaseExecutionRead: "lease.execution.read",
  leaseExecutionManage: "lease.execution.manage",
  leaseExecutionSign: "lease.execution.sign",
  moveInRead: "move_in.read",
  moveInManage: "move_in.manage",
  moveOutRead: "move_out.read",
  moveOutManage: "move_out.manage",
  depositSettlementManage: "deposit.settlement.manage",
  depositSettlementApprove: "deposit.settlement.approve",
  depositRefundRecord: "deposit.refund.record",
  leaseClose: "lease.close",
  aiUse: "ai.use",
  aiCommandCenter: "ai.command_center",
  aiPropose: "ai.propose",
  aiApprove: "ai.approve",
  jobRetry: "job.retry",
  aiAutonomyRead: "ai.autonomy.read",
  aiAutonomyManage: "ai.autonomy.manage",
  aiAutonomyPause: "ai.autonomy.pause",
  aiEmployeeRead: "ai.employee.read",
  aiEmployeeManage: "ai.employee.manage",
  aiEmployeeOperate: "ai.employee.operate",
  conversationRead: "conversation.read",
  conversationManage: "conversation.manage",
  conversationAssign: "conversation.assign",
  communicationChannelManage: "communication_channel.manage",
  documentRead: "document.read",
  documentManage: "document.manage",
  documentTemplateManage: "document.template.manage",
  calendarRead: "calendar.read",
  calendarManage: "calendar.manage",
  integrationRead: "integration.read",
  integrationManage: "integration.manage",
  billingRead: "billing.read",
  billingManage: "billing.manage",
} as const;

export async function requirePermission(userId: string, organisationId: string, permission: string) {
  if (!isUuid(organisationId)) throw forbidden();
  const membership = await db.organisationMember.findFirst({
    where: { userId, organisationId, status: "ACTIVE", archivedAt: null },
    include: { roles: { include: { role: { include: { permissions: { include: { permission: true } } } } } } },
  });
  if (!membership || !membershipHasPermission(membership.roles, permission)) {
    throw forbidden();
  }
  return membership;
}
